/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/games/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchGames"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/games/{appid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGame"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recommendGames"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uint32 */
        GameId: number;
        BuildId: string;
        /** @enum {string} */
        Lane: "mechanics" | "narrative" | "vibe" | "structure_loop";
        LaneWeights: {
            mechanics: number;
            narrative: number;
            vibe: number;
            structure_loop: number;
        };
        Seed: {
            appid: components["schemas"]["GameId"];
            weight: number;
        };
        IntentInput: {
            lane_weights: components["schemas"]["LaneWeights"];
            include: string[];
            exclude: string[];
            text: string | null;
        };
        RecommendationRequest: {
            seeds: components["schemas"]["Seed"][];
            intent: components["schemas"]["IntentInput"];
            limit: number;
        };
        NormalizedIntent: components["schemas"]["IntentInput"] & {
            seeds: components["schemas"]["Seed"][];
        };
        Game: {
            appid: components["schemas"]["GameId"];
            name: string;
            short_description: string;
            release_year?: number | null;
            /** Format: uri */
            header_image_url?: string | null;
            /** Format: uri */
            steam_url: string;
        };
        GameSearchResponse: {
            games: components["schemas"]["Game"][];
        };
        Evidence: {
            id: string;
            appid: components["schemas"]["GameId"];
            source: string;
            excerpt: string;
        };
        ScoreContribution: {
            key: string;
            label: string;
            lane?: components["schemas"]["Lane"] | null;
            value: number;
            evidence_ids: string[];
        };
        Recommendation: {
            rank: number;
            game: components["schemas"]["Game"];
            score: number;
            contributions: components["schemas"]["ScoreContribution"][];
            matched_concepts: string[];
            explanation: string;
            evidence: components["schemas"]["Evidence"][];
        };
        RetrievalState: {
            /** @enum {string} */
            mode: "candidate_graph" | "dynamic_vector" | "sparse_fallback";
            reduced_confidence: boolean;
            reason?: string | null;
        };
        RecommendationResponse: {
            build_id: components["schemas"]["BuildId"];
            normalized_intent: components["schemas"]["NormalizedIntent"];
            retrieval: components["schemas"]["RetrievalState"];
            results: components["schemas"]["Recommendation"][];
        };
        HealthResponse: {
            /** @constant */
            status: "ok";
            build_id: components["schemas"]["BuildId"];
        };
        ReadyResponse: {
            /** @constant */
            status: "ready";
            build_id: components["schemas"]["BuildId"];
        };
        ConfigResponse: {
            build_id: components["schemas"]["BuildId"];
            max_results: number;
            max_body_bytes: number;
            lanes: components["schemas"]["Lane"][];
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
            };
            request_id: string;
        };
    };
    responses: {
        /** @description Typed request or service error. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        AppId: components["schemas"]["GameId"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service loaded and validated one immutable build. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            503: components["responses"]["Error"];
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public product and request limits. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    searchGames: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Title matches in deterministic display order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameSearchResponse"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getGame: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appid: components["parameters"]["AppId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public game metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Game"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    recommendGames: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationRequest"];
            };
        };
        responses: {
            /** @description Deterministic ranking for normalized intent and active build. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            400: components["responses"]["Error"];
            413: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
}
