[package]
name = "nextsteam-python"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "nextsteam_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
domain.workspace = true
pyo3.workspace = true
recommendation-core.workspace = true
serde_json.workspace = true
